{% set import_path = "github.com/segmentio/terraform-docs" %}
{% set version = "0.7.0" %}
	
{% set name = import_path.split('/')[-1] %}
{% set pkg_src = ('src/'+import_path).replace("/", os.sep) %}
	
package:
  name: go-{{ name|lower }}
  version: "0.7.0"

source:
  - folder: {{ pkg_src }}
    url: https://{{ import_path }}/archive/v{{version}}.tar.gz
    sha256: ec0b3b95d61a348349a34650a3535ab7165eaaa49380abbfe13d2b0b7ee067f5

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - go install -v
        -ldflags "-X main.version={{ version }}"
        .

requirements:
  build:
    - {{ compiler("go") }}

test:
  commands:
    - which terraform-docs  # [not win]
    - where terraform-docs  # [win]
    - terraform-docs --help

about:
  home: https://{{ import_path }}

  license: MIT
  license_family: MIT
  license_file: {{ pkg_src }}/LICENSE
  summary: 'Generate docs from Terraform modules'

extra:
  recipe-maintainers:
    - pierrsc
